{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.2.jar",
          "url": "aaptcompiler-8.4.2.jar",
          "size": 499315,
          "sha512": "4cf787b76647a703819e64db8ba9558738b94d98e6d9c5347d8ded0f45f5048a6090f2684611b75c760040cad583cfc407f6edec02e97ae1fcd27ae3493ec2df",
          "sha256": "c8089ca4458d0cca55cd4e296b6d39d9f9208d3ad5efee58dad59b0a17b4f902",
          "sha1": "b12bd6a916badc5bc83d939ad8f46413497b5754",
          "md5": "ec8fec5089af9600f7dd4ed1d10de115"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.4.2-11315950"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.4.2.jar",
          "url": "aaptcompiler-8.4.2.jar",
          "size": 499315,
          "sha512": "4cf787b76647a703819e64db8ba9558738b94d98e6d9c5347d8ded0f45f5048a6090f2684611b75c760040cad583cfc407f6edec02e97ae1fcd27ae3493ec2df",
          "sha256": "c8089ca4458d0cca55cd4e296b6d39d9f9208d3ad5efee58dad59b0a17b4f902",
          "sha1": "b12bd6a916badc5bc83d939ad8f46413497b5754",
          "md5": "ec8fec5089af9600f7dd4ed1d10de115"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.2-javadoc.jar",
          "url": "aaptcompiler-8.4.2-javadoc.jar",
          "size": 81065,
          "sha512": "55fe4c99d831f9c3a5e131e6525137d4f2ee1ffd6c0c46fbefc70c381cf898d942f3656738f7efce18f3aed6b1075fd555a3a691de4ad325aba916264d9287ec",
          "sha256": "9df4145cb7c27c248efaf99bfab637947ad30dedf3db695c79fedd1dd454cbd8",
          "sha1": "ef7803bb9a2dcf70ff6d3a4ec3d911a313c7082a",
          "md5": "fe3c4e49b22d1bad2f61a236ea7ee4e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.4.2-sources.jar",
          "url": "aaptcompiler-8.4.2-sources.jar",
          "size": 152981,
          "sha512": "f4af4244c033185d31efc466ef8f2471ff7dcd6f1b977b80a3b26a8a9061c391851642c5c27059cba156990acc5b727ad8e8c9e917d969d4d178942c8addfc39",
          "sha256": "f859077f58aecf722e9ad5dd8748fb66c22764462c6c8bebcf4ffe1f4af12591",
          "sha1": "8585c1e39de320ac65913e7b047e5bbcdf016753",
          "md5": "840e660cf91ecef8574206ad974621f0"
        }
      ]
    }
  ]
}
