{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.4.2-11315950",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.2-11315950.jar",
          "url": "aapt2-proto-8.4.2-11315950.jar",
          "size": 712652,
          "sha512": "e4782cd17e95262a2f7df3483d9c9ea7ef7bbd02b19cb77544e4dbe2f10f3a90afc44746435d194e15cbb418bcd4cd72ba0d5dc40b3d6f2f1660e2fd96d3627e",
          "sha256": "66a589c25b2aa3d9b3daa96f07f262e3a157e43e50024234ff419b0578439645",
          "sha1": "0b0481fb53c3f7d73de0ef997eabcb6b6231c4df",
          "md5": "cd010af0258b96990f082bfb370ed7eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.4.2-11315950.jar",
          "url": "aapt2-proto-8.4.2-11315950.jar",
          "size": 712652,
          "sha512": "e4782cd17e95262a2f7df3483d9c9ea7ef7bbd02b19cb77544e4dbe2f10f3a90afc44746435d194e15cbb418bcd4cd72ba0d5dc40b3d6f2f1660e2fd96d3627e",
          "sha256": "66a589c25b2aa3d9b3daa96f07f262e3a157e43e50024234ff419b0578439645",
          "sha1": "0b0481fb53c3f7d73de0ef997eabcb6b6231c4df",
          "md5": "cd010af0258b96990f082bfb370ed7eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.2-11315950-javadoc.jar",
          "url": "aapt2-proto-8.4.2-11315950-javadoc.jar",
          "size": 1063962,
          "sha512": "3a04c4b7f7729b829de6dc2ca6b4a17c97a84a339971d6c900defbc2c8be142057f4703431f5f6a152ddb88394cff39c1efe596717162b5c333db1c0d13c7219",
          "sha256": "7f70ac8345bf4eac085e7c9e814392bf1fb27562a9c086092bd66854c0e91e0b",
          "sha1": "8f43c524ff5cf2d0790d3791c81b9746882e1e87",
          "md5": "3235a208d816198fd02bdda1ea37ccc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.4.2-11315950-sources.jar",
          "url": "aapt2-proto-8.4.2-11315950-sources.jar",
          "size": 396230,
          "sha512": "8c8e7681378de61e72ec2668e5b38cf9774977b133ed901a40a1fc14153297f412c8bd371977ed2b434479bfea4b98409c954e10e7f74d04df6403b68e2fb215",
          "sha256": "9b865a3deb082dc4213bd9f44174ae82ed8c17f54715e38c0900ee49ff6635a0",
          "sha1": "3cc8473331169c1cb651eed445bb555da6ad3282",
          "md5": "2d98d2675e1b64611e68a9a0a08b60de"
        }
      ]
    }
  ]
}
