{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.2.jar",
          "url": "manifest-merger-31.4.2.jar",
          "size": 246091,
          "sha512": "3b751ad75afcae45477fea53c7a32b29eabae3e939948be5e6af2dc57ebaefafa3eb02e4db057bd2c528291ec0ff670e8db6332e192c4f5b1d8e40448d4806a3",
          "sha256": "0b55cf1d17710a66cf0a229d6a560392a6320bcf7b6b3690e10cd90a4cad4694",
          "sha1": "d834b82b85e92dbf6fe3675039d567520a35a005",
          "md5": "1aa7a3e08d92c84b4b090b9b8795b62e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.4.2.jar",
          "url": "manifest-merger-31.4.2.jar",
          "size": 246091,
          "sha512": "3b751ad75afcae45477fea53c7a32b29eabae3e939948be5e6af2dc57ebaefafa3eb02e4db057bd2c528291ec0ff670e8db6332e192c4f5b1d8e40448d4806a3",
          "sha256": "0b55cf1d17710a66cf0a229d6a560392a6320bcf7b6b3690e10cd90a4cad4694",
          "sha1": "d834b82b85e92dbf6fe3675039d567520a35a005",
          "md5": "1aa7a3e08d92c84b4b090b9b8795b62e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.2-javadoc.jar",
          "url": "manifest-merger-31.4.2-javadoc.jar",
          "size": 274805,
          "sha512": "2beebae4902f6044a550e75bf7ed7c180b9d0c1890c4d0fe5aa86c2a3067ea7a48194d17a77373fc829e6c2bf5f67a2e470d3f097a3dfb27ae69022c7f4ded35",
          "sha256": "71e6fc6dbb8a605af9c0f375b412b48058b7cc266a3243373faaa5b89ce352cf",
          "sha1": "985c01d8b53b564355a7e708291b37e3059c2545",
          "md5": "c45fdea6a5a0fe487c7e28b89ac56aa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.4.2-sources.jar",
          "url": "manifest-merger-31.4.2-sources.jar",
          "size": 230106,
          "sha512": "94f6179b70e5a2aed62ca269bc01411407bbe1f7fd59608a2fd291502bd8efff2db7fce8fad5472125aa02a7d7db2e2ed6303a16d503212705fb42a0605c8e2c",
          "sha256": "e1680ae643b40e07d49e7625144a9a14d58f2934e4486163f15dd09bc05228f3",
          "sha1": "dd8c3d9835a4f86509b48df175c35db132c37a58",
          "md5": "a6805c656ef318b162b92a6984e88965"
        }
      ]
    }
  ]
}
