{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.2.jar",
          "url": "gradle-settings-api-8.4.2.jar",
          "size": 9856,
          "sha512": "0891d373122a60300425172391c9866cc76f9f0aad714921bfa4328dffd7807f7fa4545439b7699b489f520ec841ab32a7ddc594ac21cf042b3da1aecdb390f5",
          "sha256": "80f945de76fa05578318dd0e5bfc9393583df0adb0425c0b384f50bfeb690c87",
          "sha1": "d42c00a2542be3d6590fdcd4bfd212cc37c7fde4",
          "md5": "c3f3b93fc1964b26ade4e04b812c71be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.4.2.jar",
          "url": "gradle-settings-api-8.4.2.jar",
          "size": 9856,
          "sha512": "0891d373122a60300425172391c9866cc76f9f0aad714921bfa4328dffd7807f7fa4545439b7699b489f520ec841ab32a7ddc594ac21cf042b3da1aecdb390f5",
          "sha256": "80f945de76fa05578318dd0e5bfc9393583df0adb0425c0b384f50bfeb690c87",
          "sha1": "d42c00a2542be3d6590fdcd4bfd212cc37c7fde4",
          "md5": "c3f3b93fc1964b26ade4e04b812c71be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.2-javadoc.jar",
          "url": "gradle-settings-api-8.4.2-javadoc.jar",
          "size": 261,
          "sha512": "e24d92e54a224d2d176e90fd3ba8fe687f5661f57bb9bcbd624de917c805143527b714350e9dbc2c80c688d41d5fa30613c4b113acca8454a895814b547d0912",
          "sha256": "7ac469d6aa1dc7a1d232cfdb0f11a21626388d631f58fd84526d32d86e1c4ccd",
          "sha1": "33add37cc37eb7bcc1260df9e9131a0c024a2512",
          "md5": "305e1ce301ffd7c495f55e5c6d5c7efd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.4.2-sources.jar",
          "url": "gradle-settings-api-8.4.2-sources.jar",
          "size": 9407,
          "sha512": "c4feb2256085fc94d3f85d3b68c7c2fbcf138350ab51dfa72d81c56298fe52806121f3203e720aecd9e55f9bf164c42479eaa9d126aa6fe71c330080acff82ee",
          "sha256": "2433f35fb69a261be6ea51480415ba12f7b436964784d50d10c429d659607dc9",
          "sha1": "5acc09911037570f947b617a31de1ee7f839e746",
          "md5": "7dba4bc99432f02e0a4ae1937318d350"
        }
      ]
    }
  ]
}
