{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.2.jar",
          "url": "builder-8.4.2.jar",
          "size": 13420595,
          "sha512": "581112dcfd20a3c0b587aa20a80a84db72d8e0c4086e58b434f15fdc395ad87e865c75908fbeb1df5c7c8c14f8f4d241df072be3cc80190836480c95a3b34d1a",
          "sha256": "63868694a98cd0f7bf7c4effbf03da770f5b7e8cd734484f4e548f5dd6b9ca70",
          "sha1": "4b0e9b1e51cdfc43788817e487606e21fb5a2f46",
          "md5": "cc95b8e764f25eb47b743dee38919314"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.4.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.4.2.jar",
          "url": "builder-8.4.2.jar",
          "size": 13420595,
          "sha512": "581112dcfd20a3c0b587aa20a80a84db72d8e0c4086e58b434f15fdc395ad87e865c75908fbeb1df5c7c8c14f8f4d241df072be3cc80190836480c95a3b34d1a",
          "sha256": "63868694a98cd0f7bf7c4effbf03da770f5b7e8cd734484f4e548f5dd6b9ca70",
          "sha1": "4b0e9b1e51cdfc43788817e487606e21fb5a2f46",
          "md5": "cc95b8e764f25eb47b743dee38919314"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.2-javadoc.jar",
          "url": "builder-8.4.2-javadoc.jar",
          "size": 401060,
          "sha512": "b7c98b4f0712d93e6f67cb33204d8f29bd25f8209c27215c30573fb622ee35b1ca5838b0485ca8234fc5b63639eb038d1face9875059e7bcbb34fe19cd9a6092",
          "sha256": "7b668af5e010ca8fb5fcefc2243555fb6a6a97ca00ad9c127144d41a3e91519b",
          "sha1": "d165512fe1a87db2c56fa25cefc45e44d671ed7b",
          "md5": "5f6eac6830e805d2a11560d371524289"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.4.2-sources.jar",
          "url": "builder-8.4.2-sources.jar",
          "size": 281638,
          "sha512": "8411cc2c1ed5e19a654c4ad80cd2ef543f28a6920ced3a466925f80ec09e77b68d9b9df7bfa3caaea4c1df50e18fdaf8bd24ce3d7552da43e43d015425a8d0df",
          "sha256": "a66d112d4d713a3e50a6791f50a81a026ad068cd9d29807b576b7bd9a792858f",
          "sha1": "30576763dc9ebe8ca875b9e5d05886dd52d14415",
          "md5": "3afbfc31267b8fdaf436110504feeef2"
        }
      ]
    }
  ]
}
