{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.4.2.jar",
          "url": "builder-model-8.4.2.jar",
          "size": 122814,
          "sha512": "6330c2656bbdd4b68bdd4b57cfdd0a243e910a310f75cc03081b47c398985a0ded42d62b87b8510abc42e15bd7bee794a038acfbd20eb67fc32ae3d081a8fea6",
          "sha256": "8c94002357fe084f20440513685b31866e26f1e425dc6642a5f8c21522e39036",
          "sha1": "dad715c63c06b44c463eb88d0c6b3fe9e5dbacf5",
          "md5": "6e84b64879230a8f3ae879f9e8133fa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.4.2.jar",
          "url": "builder-model-8.4.2.jar",
          "size": 122814,
          "sha512": "6330c2656bbdd4b68bdd4b57cfdd0a243e910a310f75cc03081b47c398985a0ded42d62b87b8510abc42e15bd7bee794a038acfbd20eb67fc32ae3d081a8fea6",
          "sha256": "8c94002357fe084f20440513685b31866e26f1e425dc6642a5f8c21522e39036",
          "sha1": "dad715c63c06b44c463eb88d0c6b3fe9e5dbacf5",
          "md5": "6e84b64879230a8f3ae879f9e8133fa9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.4.2-javadoc.jar",
          "url": "builder-model-8.4.2-javadoc.jar",
          "size": 291474,
          "sha512": "36a49819e7d7e30f5a0331c3538268537a059edaaaaf1e37ba8d7bce430051cd569f4aa16b27e4a40bd914319f45972dd765948c8e0e384639989b3a0a0528fc",
          "sha256": "13b7fcbdb8a582ff6b061c7b5f68c3465bbbe6e4e6e6a67dcbb4a25437f1504b",
          "sha1": "6de56db60379bb1df2d337c02054a6d88c5dd65a",
          "md5": "2bdd193ad265f905f59a7fe675c6f58f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.4.2-sources.jar",
          "url": "builder-model-8.4.2-sources.jar",
          "size": 143166,
          "sha512": "4426a03d5f58dca0c9beb3fad9572be2f9f4af8a30dd421bc496e932c597b2fa664aa6b6d156e68baa7dcdea59c588c82c370f126b885092a929b27d0ba2a37e",
          "sha256": "d6223be1d544c065153d0fbcaa1120c36dd738a5678b50870087bf0effa5fe5e",
          "sha1": "9698337c7de4d5ae467d6c3a95e69f7bd58e7f31",
          "md5": "962015efedd4799729dc0c4594aa2f0a"
        }
      ]
    }
  ]
}
